"""Tests for the ``odoo-mcp onboarding`` guided first-run flow.

The OdooClient and the setup-wizard side effects (Keychain, Claude Desktop
registration, launch.sh) are mocked. No real network, no real Keychain,
no real subprocess.
"""

from __future__ import annotations

import io
import os
from pathlib import Path
from typing import Any

import pytest

from odoo_mcp import onboarding_cli, scan_cli, setup_wizard

_SAMPLE_CONFIG = """\
[defaults]
timeout_seconds = 30

[instances.main]
url = "https://klantx.odoo.com"
database = "klantx-prod"
credentials_env_prefix = "ODOO_MCP_MAIN"
production = false
"""


@pytest.fixture
def fake_paths(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Redirect every onboarding/wizard path into ``tmp_path``."""
    cfg_path = tmp_path / "config.toml"
    suggestions_path = tmp_path / "suggestions.toml"
    monkeypatch.setattr(setup_wizard, "DEFAULT_CONFIG_PATH", cfg_path)
    monkeypatch.setattr(setup_wizard, "_CONFIG_DIR", tmp_path)
    monkeypatch.setattr(setup_wizard, "_LAUNCH_SH", tmp_path / "launch.sh")
    monkeypatch.setattr(onboarding_cli, "DEFAULT_CONFIG_PATH", cfg_path)
    monkeypatch.setattr(onboarding_cli, "_SUGGESTIONS_PATH", suggestions_path)
    return tmp_path


def _fake_scan_result(instance: str = "main") -> scan_cli.ScanResult:
    return scan_cli.ScanResult(
        instance=instance,
        scanned_at="2026-04-30T00:00:00Z",
        odoo_reference_version="18.0",
        models_total=1088,
        fields_total=10000,
        custom_models=[
            scan_cli.ModelFinding(
                name="klantx.contract_addon",
                label="Klant Addon",
                field_count=5,
                studio=False,
            ),
        ],
        custom_fields_on_standard=[],
    )


def _patch_doctor_pass(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(onboarding_cli, "_run_doctor", lambda: 0)


def _patch_doctor_fail(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(onboarding_cli, "_run_doctor", lambda: 1)


def _patch_scan_pass(monkeypatch: pytest.MonkeyPatch, instance: str = "main") -> None:
    """Replace the inner perform_scan + build_app dependency."""
    result = _fake_scan_result(instance)
    toml_text = scan_cli.render_toml(result)

    def _fake_run_scan(name: str) -> tuple[int, str]:
        onboarding_cli._run_scan.last_summary = {  # type: ignore[attr-defined]
            "models_total": result.models_total,
            "custom_models": len(result.custom_models),
            "custom_fields": len(result.custom_fields_on_standard),
            "uid": 42,
            "login": "user@klantx.be",
        }
        return 0, toml_text

    monkeypatch.setattr(onboarding_cli, "_run_scan", _fake_run_scan)


def _stdin(monkeypatch: pytest.MonkeyPatch, lines: list[str]) -> None:
    """Feed input() calls."""
    monkeypatch.setattr("sys.stdin", io.StringIO("\n".join(lines) + "\n"))


def test_first_time_flow_runs_wizard_doctor_scan_and_writes_suggestions(
    fake_paths: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    cfg_path = fake_paths / "config.toml"
    suggestions_path = fake_paths / "suggestions.toml"

    # First-time wizard: write the config file ourselves to simulate
    # _cmd_setup completing successfully.
    def _fake_setup() -> int:
        cfg_path.write_text(_SAMPLE_CONFIG)
        os.chmod(cfg_path, 0o600)
        return 0

    monkeypatch.setattr(onboarding_cli, "_run_setup_first_time", _fake_setup)
    _patch_doctor_pass(monkeypatch)
    _patch_scan_pass(monkeypatch)
    _stdin(monkeypatch, [""])  # Press-Enter-to-begin prompt

    rc = onboarding_cli.main([])
    assert rc == 0

    assert suggestions_path.exists()
    assert suggestions_path.stat().st_mode & 0o777 == 0o600
    content = suggestions_path.read_text()
    assert "Generated by `odoo-mcp scan-custom main`" in content

    out = capsys.readouterr().out
    assert "Welcome to odoo-mcp" in out
    assert "Connected as user@klantx.be" in out
    assert "1088 models in your Odoo" in out
    assert "Restart Claude Cowork" in out


def test_existing_config_rescan_skips_setup(
    fake_paths: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    cfg_path = fake_paths / "config.toml"
    cfg_path.write_text(_SAMPLE_CONFIG)
    os.chmod(cfg_path, 0o600)

    setup_called = {"value": False}

    def _fake_setup() -> int:
        setup_called["value"] = True
        return 0

    monkeypatch.setattr(onboarding_cli, "_run_setup_first_time", _fake_setup)
    monkeypatch.setattr(onboarding_cli, "_run_setup_add", _fake_setup)
    _patch_doctor_pass(monkeypatch)
    _patch_scan_pass(monkeypatch)
    _stdin(monkeypatch, ["", "2"])  # press-enter, then choose option 2 (re-scan)

    rc = onboarding_cli.main([])
    assert rc == 0
    assert setup_called["value"] is False

    suggestions_path = fake_paths / "suggestions.toml"
    assert suggestions_path.exists()
    out = capsys.readouterr().out
    assert "Re-scanning instance 'main'" in out


def test_doctor_failure_aborts_before_scan(
    fake_paths: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    cfg_path = fake_paths / "config.toml"

    def _fake_setup() -> int:
        cfg_path.write_text(_SAMPLE_CONFIG)
        os.chmod(cfg_path, 0o600)
        return 0

    scan_called = {"value": False}

    def _scan_should_not_run(name: str) -> tuple[int, str]:
        scan_called["value"] = True
        return 0, ""

    monkeypatch.setattr(onboarding_cli, "_run_setup_first_time", _fake_setup)
    _patch_doctor_fail(monkeypatch)
    monkeypatch.setattr(onboarding_cli, "_run_scan", _scan_should_not_run)
    _stdin(monkeypatch, [""])

    rc = onboarding_cli.main([])
    assert rc == 1
    assert scan_called["value"] is False

    suggestions_path = fake_paths / "suggestions.toml"
    assert not suggestions_path.exists()

    err = capsys.readouterr().err
    assert "Doctor reported errors" in err


def test_suggestions_file_is_chmod_600(
    fake_paths: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    cfg_path = fake_paths / "config.toml"
    cfg_path.write_text(_SAMPLE_CONFIG)
    os.chmod(cfg_path, 0o600)

    _patch_doctor_pass(monkeypatch)
    _patch_scan_pass(monkeypatch)
    _stdin(monkeypatch, ["", "2"])

    rc = onboarding_cli.main([])
    assert rc == 0

    suggestions_path = fake_paths / "suggestions.toml"
    assert suggestions_path.exists()
    mode = suggestions_path.stat().st_mode & 0o777
    assert mode == 0o600, f"expected chmod 600, got {mode:o}"


def test_existing_config_cancel_does_nothing(
    fake_paths: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    cfg_path = fake_paths / "config.toml"
    cfg_path.write_text(_SAMPLE_CONFIG)
    os.chmod(cfg_path, 0o600)

    sentinel: dict[str, Any] = {"doctor": 0, "scan": 0}

    def _doctor_count() -> int:
        sentinel["doctor"] += 1
        return 0

    def _scan_count(name: str) -> tuple[int, str]:
        sentinel["scan"] += 1
        return 0, ""

    monkeypatch.setattr(onboarding_cli, "_run_doctor", _doctor_count)
    monkeypatch.setattr(onboarding_cli, "_run_scan", _scan_count)
    _stdin(monkeypatch, ["", "3"])  # cancel

    rc = onboarding_cli.main([])
    assert rc == 0
    assert sentinel["doctor"] == 0
    assert sentinel["scan"] == 0
    out = capsys.readouterr().out
    assert "Cancelled" in out


def test_help_flag_prints_usage(capsys: pytest.CaptureFixture[str]) -> None:
    rc = onboarding_cli.main(["--help"])
    assert rc == 0
    out = capsys.readouterr().out
    assert "Usage: odoo-mcp onboarding" in out
