# -*- coding: utf-8 -*-
# Small Odoo addon for deltix: per-user opt-in for long-lived API keys.
#
# Problem: many Odoo installs (Odoo Online, deployments with
# auth_password_policy enabled, certain custom modules) force non-admin
# API keys to expire after 1 day. That's the right default policy for
# password-like credentials, but it's incompatible with MCP-style
# integrations where the user generates one key and uses it for weeks.
#
# Fix: add a per-user boolean ``mcp_long_lived_keys``. When enabled,
# API keys generated by that user automatically get a 90-day expiry,
# overriding any other module's default. The flag is set by an admin
# on a per-user basis via a single checkbox on the user form.
#
# Status: tested locally only. Install on a non-prod Odoo first.

{
    "name": "MCP Long-Lived API Keys",
    "version": "1.0.0",
    "summary": "Per-user opt-in to override the 1-day API key expiry default",
    "description": (
        "Adds a per-user boolean field 'Allow long-lived MCP API keys'. "
        "When checked, API keys generated by that user get a 90-day "
        "expiry regardless of other modules' defaults. Designed for "
        "users running the odoo-mcp integration."
    ),
    "category": "Tools",
    "author": "deltix consulting",
    "website": "https://www.deltix.pro",
    "license": "MIT",
    "depends": ["base"],
    "data": [
        "views/res_users_views.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
