# -*- coding: utf-8 -*-
"""Per-user opt-in for long-lived API keys.

Adds a single boolean field ``mcp_long_lived_keys`` on ``res.users``.
When checked by an admin, API keys generated by that user get a
90-day expiry regardless of other modules' defaults (which typically
force non-admin keys to 1 day).

The override happens in ``res.users.apikeys._generate``: if the user
who is generating the key has the boolean set and no other code has
already pinned a longer expiration, we set the expiration_date to
``now + 90 days``. Existing keys are not retroactively changed.
"""

from datetime import datetime, timedelta

from odoo import api, fields, models

# Hardcoded duration. Edit here if your security policy wants a
# different number — 30 / 60 / 180 / 365 are all reasonable. Keep
# below "Never" so revocation via the standard Account Security tab
# still works.
_LONG_LIVED_DURATION_DAYS = 90


class ResUsers(models.Model):
    _inherit = "res.users"

    mcp_long_lived_keys = fields.Boolean(
        string="Allow long-lived MCP API keys",
        default=False,
        help=(
            "When enabled, API keys generated by this user automatically "
            "get a %d-day expiry instead of the system default (often 1 "
            "day for non-admins). Set this per-user for people running "
            "the odoo-mcp integration. Existing keys are not changed."
        ) % _LONG_LIVED_DURATION_DAYS,
    )

    @property
    def SELF_READABLE_FIELDS(self):  # noqa: N802 — Odoo naming
        # Allow the user themselves to see the flag in their profile.
        return super().SELF_READABLE_FIELDS + ["mcp_long_lived_keys"]


class ResUsersApikeys(models.Model):
    _inherit = "res.users.apikeys"

    @api.model
    def _generate(self, scope, name, expiration_date=None):
        """Override the default expiration for opted-in users.

        Only applies when the caller did not already specify an
        expiration_date (so an admin who explicitly picks "1 day" in
        the wizard for an opted-in user still gets 1 day). Falls back
        to the default ``_generate`` implementation in every other
        case.
        """
        user = self.env.user
        if expiration_date is None and getattr(user, "mcp_long_lived_keys", False):
            expiration_date = datetime.now() + timedelta(days=_LONG_LIVED_DURATION_DAYS)
        return super()._generate(scope, name, expiration_date)
